// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package model

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BucketMeta) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "creation_date":
			z.CreationDate, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CreationDate")
				return
			}
		case "total_size":
			z.TotalSize, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TotalSize")
				return
			}
		case "object_count":
			z.ObjectCount, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ObjectCount")
				return
			}
		case "owner":
			z.Owner, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Owner")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *BucketMeta) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "name"
	err = en.Append(0x85, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "creation_date"
	err = en.Append(0xad, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CreationDate)
	if err != nil {
		err = msgp.WrapError(err, "CreationDate")
		return
	}
	// write "total_size"
	err = en.Append(0xaa, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.TotalSize)
	if err != nil {
		err = msgp.WrapError(err, "TotalSize")
		return
	}
	// write "object_count"
	err = en.Append(0xac, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.ObjectCount)
	if err != nil {
		err = msgp.WrapError(err, "ObjectCount")
		return
	}
	// write "owner"
	err = en.Append(0xa5, 0x6f, 0x77, 0x6e, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Owner)
	if err != nil {
		err = msgp.WrapError(err, "Owner")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *BucketMeta) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "name"
	o = append(o, 0x85, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "creation_date"
	o = append(o, 0xad, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65)
	o = msgp.AppendInt64(o, z.CreationDate)
	// string "total_size"
	o = append(o, 0xaa, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt64(o, z.TotalSize)
	// string "object_count"
	o = append(o, 0xac, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt64(o, z.ObjectCount)
	// string "owner"
	o = append(o, 0xa5, 0x6f, 0x77, 0x6e, 0x65, 0x72)
	o = msgp.AppendString(o, z.Owner)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BucketMeta) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "creation_date":
			z.CreationDate, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreationDate")
				return
			}
		case "total_size":
			z.TotalSize, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalSize")
				return
			}
		case "object_count":
			z.ObjectCount, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ObjectCount")
				return
			}
		case "owner":
			z.Owner, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Owner")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BucketMeta) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 14 + msgp.Int64Size + 11 + msgp.Int64Size + 13 + msgp.Int64Size + 6 + msgp.StringPrefixSize + len(z.Owner)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *HealingLock) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "path":
			z.Path, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "acquired_at":
			z.AcquiredAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "AcquiredAt")
				return
			}
		case "expires_at":
			z.ExpiresAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ExpiresAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *HealingLock) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "id"
	err = en.Append(0x84, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "path"
	err = en.Append(0xa4, 0x70, 0x61, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Path)
	if err != nil {
		err = msgp.WrapError(err, "Path")
		return
	}
	// write "acquired_at"
	err = en.Append(0xab, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.AcquiredAt)
	if err != nil {
		err = msgp.WrapError(err, "AcquiredAt")
		return
	}
	// write "expires_at"
	err = en.Append(0xaa, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.ExpiresAt)
	if err != nil {
		err = msgp.WrapError(err, "ExpiresAt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *HealingLock) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "id"
	o = append(o, 0x84, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "path"
	o = append(o, 0xa4, 0x70, 0x61, 0x74, 0x68)
	o = msgp.AppendString(o, z.Path)
	// string "acquired_at"
	o = append(o, 0xab, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74)
	o = msgp.AppendInt64(o, z.AcquiredAt)
	// string "expires_at"
	o = append(o, 0xaa, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74)
	o = msgp.AppendInt64(o, z.ExpiresAt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *HealingLock) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "path":
			z.Path, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "acquired_at":
			z.AcquiredAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AcquiredAt")
				return
			}
		case "expires_at":
			z.ExpiresAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiresAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *HealingLock) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Path) + 12 + msgp.Int64Size + 11 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MetaData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "version":
			z.Version, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "disk_uuid":
			z.DiskUUID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DiskUUID")
				return
			}
		case "updated_at":
			z.UpdatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "buckets":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Buckets")
				return
			}
			if cap(z.Buckets) >= int(zb0002) {
				z.Buckets = (z.Buckets)[:zb0002]
			} else {
				z.Buckets = make([]BucketMeta, zb0002)
			}
			for za0001 := range z.Buckets {
				err = z.Buckets[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Buckets", za0001)
					return
				}
			}
		case "multiparts":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Multiparts")
				return
			}
			if cap(z.Multiparts) >= int(zb0003) {
				z.Multiparts = (z.Multiparts)[:zb0003]
			} else {
				z.Multiparts = make([]Multipart, zb0003)
			}
			for za0002 := range z.Multiparts {
				err = z.Multiparts[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Multiparts", za0002)
					return
				}
			}
		case "healing":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Healing")
				return
			}
			if cap(z.Healing) >= int(zb0004) {
				z.Healing = (z.Healing)[:zb0004]
			} else {
				z.Healing = make([]HealingLock, zb0004)
			}
			for za0003 := range z.Healing {
				err = z.Healing[za0003].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Healing", za0003)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MetaData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "version"
	err = en.Append(0x86, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "disk_uuid"
	err = en.Append(0xa9, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x75, 0x75, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.DiskUUID)
	if err != nil {
		err = msgp.WrapError(err, "DiskUUID")
		return
	}
	// write "updated_at"
	err = en.Append(0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	// write "buckets"
	err = en.Append(0xa7, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Buckets)))
	if err != nil {
		err = msgp.WrapError(err, "Buckets")
		return
	}
	for za0001 := range z.Buckets {
		err = z.Buckets[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Buckets", za0001)
			return
		}
	}
	// write "multiparts"
	err = en.Append(0xaa, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Multiparts)))
	if err != nil {
		err = msgp.WrapError(err, "Multiparts")
		return
	}
	for za0002 := range z.Multiparts {
		err = z.Multiparts[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Multiparts", za0002)
			return
		}
	}
	// write "healing"
	err = en.Append(0xa7, 0x68, 0x65, 0x61, 0x6c, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Healing)))
	if err != nil {
		err = msgp.WrapError(err, "Healing")
		return
	}
	for za0003 := range z.Healing {
		err = z.Healing[za0003].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Healing", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MetaData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "version"
	o = append(o, 0x86, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt64(o, z.Version)
	// string "disk_uuid"
	o = append(o, 0xa9, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x75, 0x75, 0x69, 0x64)
	o = msgp.AppendString(o, z.DiskUUID)
	// string "updated_at"
	o = append(o, 0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
	o = msgp.AppendInt64(o, z.UpdatedAt)
	// string "buckets"
	o = append(o, 0xa7, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Buckets)))
	for za0001 := range z.Buckets {
		o, err = z.Buckets[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Buckets", za0001)
			return
		}
	}
	// string "multiparts"
	o = append(o, 0xaa, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Multiparts)))
	for za0002 := range z.Multiparts {
		o, err = z.Multiparts[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Multiparts", za0002)
			return
		}
	}
	// string "healing"
	o = append(o, 0xa7, 0x68, 0x65, 0x61, 0x6c, 0x69, 0x6e, 0x67)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Healing)))
	for za0003 := range z.Healing {
		o, err = z.Healing[za0003].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Healing", za0003)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MetaData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "version":
			z.Version, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "disk_uuid":
			z.DiskUUID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiskUUID")
				return
			}
		case "updated_at":
			z.UpdatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "buckets":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Buckets")
				return
			}
			if cap(z.Buckets) >= int(zb0002) {
				z.Buckets = (z.Buckets)[:zb0002]
			} else {
				z.Buckets = make([]BucketMeta, zb0002)
			}
			for za0001 := range z.Buckets {
				bts, err = z.Buckets[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Buckets", za0001)
					return
				}
			}
		case "multiparts":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Multiparts")
				return
			}
			if cap(z.Multiparts) >= int(zb0003) {
				z.Multiparts = (z.Multiparts)[:zb0003]
			} else {
				z.Multiparts = make([]Multipart, zb0003)
			}
			for za0002 := range z.Multiparts {
				bts, err = z.Multiparts[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Multiparts", za0002)
					return
				}
			}
		case "healing":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Healing")
				return
			}
			if cap(z.Healing) >= int(zb0004) {
				z.Healing = (z.Healing)[:zb0004]
			} else {
				z.Healing = make([]HealingLock, zb0004)
			}
			for za0003 := range z.Healing {
				bts, err = z.Healing[za0003].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Healing", za0003)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MetaData) Msgsize() (s int) {
	s = 1 + 8 + msgp.Int64Size + 10 + msgp.StringPrefixSize + len(z.DiskUUID) + 11 + msgp.Int64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Buckets {
		s += z.Buckets[za0001].Msgsize()
	}
	s += 11 + msgp.ArrayHeaderSize
	for za0002 := range z.Multiparts {
		s += z.Multiparts[za0002].Msgsize()
	}
	s += 8 + msgp.ArrayHeaderSize
	for za0003 := range z.Healing {
		s += z.Healing[za0003].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Multipart) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "upload_id":
			z.UploadID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UploadID")
				return
			}
		case "bucket":
			z.Bucket, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Bucket")
				return
			}
		case "key":
			z.Key, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "initiated":
			z.Initiated, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Initiated")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Multipart) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "upload_id"
	err = en.Append(0x84, 0xa9, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.UploadID)
	if err != nil {
		err = msgp.WrapError(err, "UploadID")
		return
	}
	// write "bucket"
	err = en.Append(0xa6, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Bucket)
	if err != nil {
		err = msgp.WrapError(err, "Bucket")
		return
	}
	// write "key"
	err = en.Append(0xa3, 0x6b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Key)
	if err != nil {
		err = msgp.WrapError(err, "Key")
		return
	}
	// write "initiated"
	err = en.Append(0xa9, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Initiated)
	if err != nil {
		err = msgp.WrapError(err, "Initiated")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Multipart) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "upload_id"
	o = append(o, 0x84, 0xa9, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.UploadID)
	// string "bucket"
	o = append(o, 0xa6, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74)
	o = msgp.AppendString(o, z.Bucket)
	// string "key"
	o = append(o, 0xa3, 0x6b, 0x65, 0x79)
	o = msgp.AppendString(o, z.Key)
	// string "initiated"
	o = append(o, 0xa9, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64)
	o = msgp.AppendInt64(o, z.Initiated)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Multipart) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "upload_id":
			z.UploadID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UploadID")
				return
			}
		case "bucket":
			z.Bucket, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bucket")
				return
			}
		case "key":
			z.Key, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "initiated":
			z.Initiated, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Initiated")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Multipart) Msgsize() (s int) {
	s = 1 + 10 + msgp.StringPrefixSize + len(z.UploadID) + 7 + msgp.StringPrefixSize + len(z.Bucket) + 4 + msgp.StringPrefixSize + len(z.Key) + 10 + msgp.Int64Size
	return
}
