// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package model

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BucketPermission) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "bucket_name":
			z.BucketName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BucketName")
				return
			}
		case "can_read":
			z.CanRead, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "CanRead")
				return
			}
		case "can_write":
			z.CanWrite, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "CanWrite")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z BucketPermission) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "bucket_name"
	err = en.Append(0x83, 0xab, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.BucketName)
	if err != nil {
		err = msgp.WrapError(err, "BucketName")
		return
	}
	// write "can_read"
	err = en.Append(0xa8, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.CanRead)
	if err != nil {
		err = msgp.WrapError(err, "CanRead")
		return
	}
	// write "can_write"
	err = en.Append(0xa9, 0x63, 0x61, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.CanWrite)
	if err != nil {
		err = msgp.WrapError(err, "CanWrite")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z BucketPermission) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "bucket_name"
	o = append(o, 0x83, 0xab, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.BucketName)
	// string "can_read"
	o = append(o, 0xa8, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64)
	o = msgp.AppendBool(o, z.CanRead)
	// string "can_write"
	o = append(o, 0xa9, 0x63, 0x61, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65)
	o = msgp.AppendBool(o, z.CanWrite)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BucketPermission) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "bucket_name":
			z.BucketName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BucketName")
				return
			}
		case "can_read":
			z.CanRead, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CanRead")
				return
			}
		case "can_write":
			z.CanWrite, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CanWrite")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z BucketPermission) Msgsize() (s int) {
	s = 1 + 12 + msgp.StringPrefixSize + len(z.BucketName) + 9 + msgp.BoolSize + 10 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *User) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "username":
			z.Username, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "password_hash":
			z.PasswordHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PasswordHash")
				return
			}
		case "display_name":
			z.DisplayName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DisplayName")
				return
			}
		case "roles":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Roles")
				return
			}
			if cap(z.Roles) >= int(zb0002) {
				z.Roles = (z.Roles)[:zb0002]
			} else {
				z.Roles = make([]string, zb0002)
			}
			for za0001 := range z.Roles {
				z.Roles[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Roles", za0001)
					return
				}
			}
		case "provider":
			z.Provider, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Provider")
				return
			}
		case "external_id":
			z.ExternalID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ExternalID")
				return
			}
		case "is_bootstrap":
			z.IsBootstrap, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsBootstrap")
				return
			}
		case "created_at":
			z.CreatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "updated_at":
			z.UpdatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "bucket_permissions":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "BucketPermissions")
				return
			}
			if cap(z.BucketPermissions) >= int(zb0003) {
				z.BucketPermissions = (z.BucketPermissions)[:zb0003]
			} else {
				z.BucketPermissions = make([]BucketPermission, zb0003)
			}
			for za0002 := range z.BucketPermissions {
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "BucketPermissions", za0002)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "BucketPermissions", za0002)
						return
					}
					switch msgp.UnsafeString(field) {
					case "bucket_name":
						z.BucketPermissions[za0002].BucketName, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "BucketName")
							return
						}
					case "can_read":
						z.BucketPermissions[za0002].CanRead, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanRead")
							return
						}
					case "can_write":
						z.BucketPermissions[za0002].CanWrite, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanWrite")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *User) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "id"
	err = en.Append(0x8b, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "username"
	err = en.Append(0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Username)
	if err != nil {
		err = msgp.WrapError(err, "Username")
		return
	}
	// write "password_hash"
	err = en.Append(0xad, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.PasswordHash)
	if err != nil {
		err = msgp.WrapError(err, "PasswordHash")
		return
	}
	// write "display_name"
	err = en.Append(0xac, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.DisplayName)
	if err != nil {
		err = msgp.WrapError(err, "DisplayName")
		return
	}
	// write "roles"
	err = en.Append(0xa5, 0x72, 0x6f, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Roles)))
	if err != nil {
		err = msgp.WrapError(err, "Roles")
		return
	}
	for za0001 := range z.Roles {
		err = en.WriteString(z.Roles[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Roles", za0001)
			return
		}
	}
	// write "provider"
	err = en.Append(0xa8, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Provider)
	if err != nil {
		err = msgp.WrapError(err, "Provider")
		return
	}
	// write "external_id"
	err = en.Append(0xab, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ExternalID)
	if err != nil {
		err = msgp.WrapError(err, "ExternalID")
		return
	}
	// write "is_bootstrap"
	err = en.Append(0xac, 0x69, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsBootstrap)
	if err != nil {
		err = msgp.WrapError(err, "IsBootstrap")
		return
	}
	// write "created_at"
	err = en.Append(0xaa, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CreatedAt)
	if err != nil {
		err = msgp.WrapError(err, "CreatedAt")
		return
	}
	// write "updated_at"
	err = en.Append(0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	// write "bucket_permissions"
	err = en.Append(0xb2, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.BucketPermissions)))
	if err != nil {
		err = msgp.WrapError(err, "BucketPermissions")
		return
	}
	for za0002 := range z.BucketPermissions {
		// map header, size 3
		// write "bucket_name"
		err = en.Append(0x83, 0xab, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.BucketPermissions[za0002].BucketName)
		if err != nil {
			err = msgp.WrapError(err, "BucketPermissions", za0002, "BucketName")
			return
		}
		// write "can_read"
		err = en.Append(0xa8, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64)
		if err != nil {
			return
		}
		err = en.WriteBool(z.BucketPermissions[za0002].CanRead)
		if err != nil {
			err = msgp.WrapError(err, "BucketPermissions", za0002, "CanRead")
			return
		}
		// write "can_write"
		err = en.Append(0xa9, 0x63, 0x61, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65)
		if err != nil {
			return
		}
		err = en.WriteBool(z.BucketPermissions[za0002].CanWrite)
		if err != nil {
			err = msgp.WrapError(err, "BucketPermissions", za0002, "CanWrite")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *User) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "id"
	o = append(o, 0x8b, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "username"
	o = append(o, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Username)
	// string "password_hash"
	o = append(o, 0xad, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.PasswordHash)
	// string "display_name"
	o = append(o, 0xac, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.DisplayName)
	// string "roles"
	o = append(o, 0xa5, 0x72, 0x6f, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Roles)))
	for za0001 := range z.Roles {
		o = msgp.AppendString(o, z.Roles[za0001])
	}
	// string "provider"
	o = append(o, 0xa8, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72)
	o = msgp.AppendString(o, z.Provider)
	// string "external_id"
	o = append(o, 0xab, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ExternalID)
	// string "is_bootstrap"
	o = append(o, 0xac, 0x69, 0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70)
	o = msgp.AppendBool(o, z.IsBootstrap)
	// string "created_at"
	o = append(o, 0xaa, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
	o = msgp.AppendInt64(o, z.CreatedAt)
	// string "updated_at"
	o = append(o, 0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74)
	o = msgp.AppendInt64(o, z.UpdatedAt)
	// string "bucket_permissions"
	o = append(o, 0xb2, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.BucketPermissions)))
	for za0002 := range z.BucketPermissions {
		// map header, size 3
		// string "bucket_name"
		o = append(o, 0x83, 0xab, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z.BucketPermissions[za0002].BucketName)
		// string "can_read"
		o = append(o, 0xa8, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64)
		o = msgp.AppendBool(o, z.BucketPermissions[za0002].CanRead)
		// string "can_write"
		o = append(o, 0xa9, 0x63, 0x61, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65)
		o = msgp.AppendBool(o, z.BucketPermissions[za0002].CanWrite)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *User) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "username":
			z.Username, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "password_hash":
			z.PasswordHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PasswordHash")
				return
			}
		case "display_name":
			z.DisplayName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DisplayName")
				return
			}
		case "roles":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Roles")
				return
			}
			if cap(z.Roles) >= int(zb0002) {
				z.Roles = (z.Roles)[:zb0002]
			} else {
				z.Roles = make([]string, zb0002)
			}
			for za0001 := range z.Roles {
				z.Roles[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Roles", za0001)
					return
				}
			}
		case "provider":
			z.Provider, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Provider")
				return
			}
		case "external_id":
			z.ExternalID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExternalID")
				return
			}
		case "is_bootstrap":
			z.IsBootstrap, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsBootstrap")
				return
			}
		case "created_at":
			z.CreatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "updated_at":
			z.UpdatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "bucket_permissions":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BucketPermissions")
				return
			}
			if cap(z.BucketPermissions) >= int(zb0003) {
				z.BucketPermissions = (z.BucketPermissions)[:zb0003]
			} else {
				z.BucketPermissions = make([]BucketPermission, zb0003)
			}
			for za0002 := range z.BucketPermissions {
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "BucketPermissions", za0002)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "BucketPermissions", za0002)
						return
					}
					switch msgp.UnsafeString(field) {
					case "bucket_name":
						z.BucketPermissions[za0002].BucketName, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "BucketName")
							return
						}
					case "can_read":
						z.BucketPermissions[za0002].CanRead, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanRead")
							return
						}
					case "can_write":
						z.BucketPermissions[za0002].CanWrite, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanWrite")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *User) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 9 + msgp.StringPrefixSize + len(z.Username) + 14 + msgp.StringPrefixSize + len(z.PasswordHash) + 13 + msgp.StringPrefixSize + len(z.DisplayName) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Roles {
		s += msgp.StringPrefixSize + len(z.Roles[za0001])
	}
	s += 9 + msgp.StringPrefixSize + len(z.Provider) + 12 + msgp.StringPrefixSize + len(z.ExternalID) + 13 + msgp.BoolSize + 11 + msgp.Int64Size + 11 + msgp.Int64Size + 19 + msgp.ArrayHeaderSize
	for za0002 := range z.BucketPermissions {
		s += 1 + 12 + msgp.StringPrefixSize + len(z.BucketPermissions[za0002].BucketName) + 9 + msgp.BoolSize + 10 + msgp.BoolSize
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *UserPersistent) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Username":
			z.Username, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "PasswordHash":
			z.PasswordHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PasswordHash")
				return
			}
		case "DisplayName":
			z.DisplayName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DisplayName")
				return
			}
		case "Roles":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Roles")
				return
			}
			if cap(z.Roles) >= int(zb0002) {
				z.Roles = (z.Roles)[:zb0002]
			} else {
				z.Roles = make([]string, zb0002)
			}
			for za0001 := range z.Roles {
				z.Roles[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Roles", za0001)
					return
				}
			}
		case "Provider":
			z.Provider, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Provider")
				return
			}
		case "ExternalID":
			z.ExternalID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ExternalID")
				return
			}
		case "IsBootstrap":
			z.IsBootstrap, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsBootstrap")
				return
			}
		case "CreatedAt":
			z.CreatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "UpdatedAt":
			z.UpdatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "BucketPermissions":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "BucketPermissions")
				return
			}
			if cap(z.BucketPermissions) >= int(zb0003) {
				z.BucketPermissions = (z.BucketPermissions)[:zb0003]
			} else {
				z.BucketPermissions = make([]BucketPermission, zb0003)
			}
			for za0002 := range z.BucketPermissions {
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "BucketPermissions", za0002)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "BucketPermissions", za0002)
						return
					}
					switch msgp.UnsafeString(field) {
					case "bucket_name":
						z.BucketPermissions[za0002].BucketName, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "BucketName")
							return
						}
					case "can_read":
						z.BucketPermissions[za0002].CanRead, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanRead")
							return
						}
					case "can_write":
						z.BucketPermissions[za0002].CanWrite, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanWrite")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *UserPersistent) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "ID"
	err = en.Append(0x8b, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Username"
	err = en.Append(0xa8, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Username)
	if err != nil {
		err = msgp.WrapError(err, "Username")
		return
	}
	// write "PasswordHash"
	err = en.Append(0xac, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.PasswordHash)
	if err != nil {
		err = msgp.WrapError(err, "PasswordHash")
		return
	}
	// write "DisplayName"
	err = en.Append(0xab, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.DisplayName)
	if err != nil {
		err = msgp.WrapError(err, "DisplayName")
		return
	}
	// write "Roles"
	err = en.Append(0xa5, 0x52, 0x6f, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Roles)))
	if err != nil {
		err = msgp.WrapError(err, "Roles")
		return
	}
	for za0001 := range z.Roles {
		err = en.WriteString(z.Roles[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Roles", za0001)
			return
		}
	}
	// write "Provider"
	err = en.Append(0xa8, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Provider)
	if err != nil {
		err = msgp.WrapError(err, "Provider")
		return
	}
	// write "ExternalID"
	err = en.Append(0xaa, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ExternalID)
	if err != nil {
		err = msgp.WrapError(err, "ExternalID")
		return
	}
	// write "IsBootstrap"
	err = en.Append(0xab, 0x49, 0x73, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsBootstrap)
	if err != nil {
		err = msgp.WrapError(err, "IsBootstrap")
		return
	}
	// write "CreatedAt"
	err = en.Append(0xa9, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CreatedAt)
	if err != nil {
		err = msgp.WrapError(err, "CreatedAt")
		return
	}
	// write "UpdatedAt"
	err = en.Append(0xa9, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	// write "BucketPermissions"
	err = en.Append(0xb1, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.BucketPermissions)))
	if err != nil {
		err = msgp.WrapError(err, "BucketPermissions")
		return
	}
	for za0002 := range z.BucketPermissions {
		// map header, size 3
		// write "bucket_name"
		err = en.Append(0x83, 0xab, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.BucketPermissions[za0002].BucketName)
		if err != nil {
			err = msgp.WrapError(err, "BucketPermissions", za0002, "BucketName")
			return
		}
		// write "can_read"
		err = en.Append(0xa8, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64)
		if err != nil {
			return
		}
		err = en.WriteBool(z.BucketPermissions[za0002].CanRead)
		if err != nil {
			err = msgp.WrapError(err, "BucketPermissions", za0002, "CanRead")
			return
		}
		// write "can_write"
		err = en.Append(0xa9, 0x63, 0x61, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65)
		if err != nil {
			return
		}
		err = en.WriteBool(z.BucketPermissions[za0002].CanWrite)
		if err != nil {
			err = msgp.WrapError(err, "BucketPermissions", za0002, "CanWrite")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *UserPersistent) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "ID"
	o = append(o, 0x8b, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "Username"
	o = append(o, 0xa8, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Username)
	// string "PasswordHash"
	o = append(o, 0xac, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.PasswordHash)
	// string "DisplayName"
	o = append(o, 0xab, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.DisplayName)
	// string "Roles"
	o = append(o, 0xa5, 0x52, 0x6f, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Roles)))
	for za0001 := range z.Roles {
		o = msgp.AppendString(o, z.Roles[za0001])
	}
	// string "Provider"
	o = append(o, 0xa8, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72)
	o = msgp.AppendString(o, z.Provider)
	// string "ExternalID"
	o = append(o, 0xaa, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44)
	o = msgp.AppendString(o, z.ExternalID)
	// string "IsBootstrap"
	o = append(o, 0xab, 0x49, 0x73, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70)
	o = msgp.AppendBool(o, z.IsBootstrap)
	// string "CreatedAt"
	o = append(o, 0xa9, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74)
	o = msgp.AppendInt64(o, z.CreatedAt)
	// string "UpdatedAt"
	o = append(o, 0xa9, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74)
	o = msgp.AppendInt64(o, z.UpdatedAt)
	// string "BucketPermissions"
	o = append(o, 0xb1, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.BucketPermissions)))
	for za0002 := range z.BucketPermissions {
		// map header, size 3
		// string "bucket_name"
		o = append(o, 0x83, 0xab, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z.BucketPermissions[za0002].BucketName)
		// string "can_read"
		o = append(o, 0xa8, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64)
		o = msgp.AppendBool(o, z.BucketPermissions[za0002].CanRead)
		// string "can_write"
		o = append(o, 0xa9, 0x63, 0x61, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65)
		o = msgp.AppendBool(o, z.BucketPermissions[za0002].CanWrite)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UserPersistent) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Username":
			z.Username, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "PasswordHash":
			z.PasswordHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PasswordHash")
				return
			}
		case "DisplayName":
			z.DisplayName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DisplayName")
				return
			}
		case "Roles":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Roles")
				return
			}
			if cap(z.Roles) >= int(zb0002) {
				z.Roles = (z.Roles)[:zb0002]
			} else {
				z.Roles = make([]string, zb0002)
			}
			for za0001 := range z.Roles {
				z.Roles[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Roles", za0001)
					return
				}
			}
		case "Provider":
			z.Provider, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Provider")
				return
			}
		case "ExternalID":
			z.ExternalID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExternalID")
				return
			}
		case "IsBootstrap":
			z.IsBootstrap, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsBootstrap")
				return
			}
		case "CreatedAt":
			z.CreatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "UpdatedAt":
			z.UpdatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		case "BucketPermissions":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BucketPermissions")
				return
			}
			if cap(z.BucketPermissions) >= int(zb0003) {
				z.BucketPermissions = (z.BucketPermissions)[:zb0003]
			} else {
				z.BucketPermissions = make([]BucketPermission, zb0003)
			}
			for za0002 := range z.BucketPermissions {
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "BucketPermissions", za0002)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "BucketPermissions", za0002)
						return
					}
					switch msgp.UnsafeString(field) {
					case "bucket_name":
						z.BucketPermissions[za0002].BucketName, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "BucketName")
							return
						}
					case "can_read":
						z.BucketPermissions[za0002].CanRead, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanRead")
							return
						}
					case "can_write":
						z.BucketPermissions[za0002].CanWrite, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002, "CanWrite")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "BucketPermissions", za0002)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UserPersistent) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 9 + msgp.StringPrefixSize + len(z.Username) + 13 + msgp.StringPrefixSize + len(z.PasswordHash) + 12 + msgp.StringPrefixSize + len(z.DisplayName) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Roles {
		s += msgp.StringPrefixSize + len(z.Roles[za0001])
	}
	s += 9 + msgp.StringPrefixSize + len(z.Provider) + 11 + msgp.StringPrefixSize + len(z.ExternalID) + 12 + msgp.BoolSize + 10 + msgp.Int64Size + 10 + msgp.Int64Size + 18 + msgp.ArrayHeaderSize
	for za0002 := range z.BucketPermissions {
		s += 1 + 12 + msgp.StringPrefixSize + len(z.BucketPermissions[za0002].BucketName) + 9 + msgp.BoolSize + 10 + msgp.BoolSize
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *UserStore) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Version":
			z.Version, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "Users":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Users")
				return
			}
			if cap(z.Users) >= int(zb0002) {
				z.Users = (z.Users)[:zb0002]
			} else {
				z.Users = make([]UserPersistent, zb0002)
			}
			for za0001 := range z.Users {
				err = z.Users[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Users", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *UserStore) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Version"
	err = en.Append(0x82, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "Users"
	err = en.Append(0xa5, 0x55, 0x73, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Users)))
	if err != nil {
		err = msgp.WrapError(err, "Users")
		return
	}
	for za0001 := range z.Users {
		err = z.Users[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Users", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *UserStore) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Version"
	o = append(o, 0x82, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt64(o, z.Version)
	// string "Users"
	o = append(o, 0xa5, 0x55, 0x73, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Users)))
	for za0001 := range z.Users {
		o, err = z.Users[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Users", za0001)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UserStore) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Version":
			z.Version, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "Users":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Users")
				return
			}
			if cap(z.Users) >= int(zb0002) {
				z.Users = (z.Users)[:zb0002]
			} else {
				z.Users = make([]UserPersistent, zb0002)
			}
			for za0001 := range z.Users {
				bts, err = z.Users[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Users", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UserStore) Msgsize() (s int) {
	s = 1 + 8 + msgp.Int64Size + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Users {
		s += z.Users[za0001].Msgsize()
	}
	return
}
